// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSROGHrwa5Wk7nigEImklNSk2KUo8Ohfg',
    appId: '1:159094534915:web:a4276354369f76c69eef36',
    messagingSenderId: '159094534915',
    projectId: 'expense-tracker-8bde1',
    authDomain: 'expense-tracker-8bde1.firebaseapp.com',
    storageBucket: 'expense-tracker-8bde1.firebasestorage.app',
    measurementId: 'G-0KCJ5497C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSLz5QU4976-vYxgUjV7fsXQ1Utrxn76A',
    appId: '1:159094534915:android:fc82e6123513dd469eef36',
    messagingSenderId: '159094534915',
    projectId: 'expense-tracker-8bde1',
    storageBucket: 'expense-tracker-8bde1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8SWXVraSuK1v8X6zpWh6V1eBUJEOweu8',
    appId: '1:159094534915:ios:844cd575122298af9eef36',
    messagingSenderId: '159094534915',
    projectId: 'expense-tracker-8bde1',
    storageBucket: 'expense-tracker-8bde1.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8SWXVraSuK1v8X6zpWh6V1eBUJEOweu8',
    appId: '1:159094534915:ios:844cd575122298af9eef36',
    messagingSenderId: '159094534915',
    projectId: 'expense-tracker-8bde1',
    storageBucket: 'expense-tracker-8bde1.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSROGHrwa5Wk7nigEImklNSk2KUo8Ohfg',
    appId: '1:159094534915:web:1d19194e3d94d4e89eef36',
    messagingSenderId: '159094534915',
    projectId: 'expense-tracker-8bde1',
    authDomain: 'expense-tracker-8bde1.firebaseapp.com',
    storageBucket: 'expense-tracker-8bde1.firebasestorage.app',
    measurementId: 'G-5PC9L31WNT',
  );
}
